[package]
name = "collector"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pnet = "0.27.2"
rusqlite = "0.26.2"
chrono = "0.4.19"
byteorder = "1.4.3"
clap = "3.0"
